name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version(v1.0.0)'
        required: true

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install Pnpm
        run: npm install -g pnpm@^6

      - name: Install Dependencies
        run: pnpm install

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: pnpm run bump && pnpm install
          publish: pnpm run release
          commit: Release ${{ github.event.inputs.version }}
          title: Release ${{ github.event.inputs.version }}
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
